import { Project } from './project.model';

export const ProjectsDB: Project[] = [

    // {
    //     position: 'left',
    //     title: 'Portfolio',
    //     lead_text: 'My portfolio site',
    //     date: '2019-06-01',
    //     tags: ['Angular', 'TypeScript'],
    //     featured_image: '../assets/00-portfolio-site.png',
    //     project_link: '',
    //     button_icon: 'fab fa-angular fa-lg',
    //     button_text: 'Visit project',
    //     categories: 'development',
    // },
    {
        position: 'right',
        title: 'Angular Workshop',
        lead_text: 'Angular Core and Reactive Angular with NgRx / Frontend Masters',
        date: '2019-02-03',
        tags: ['NX', 'RxJS', 'Angular', 'Material', 'TypeScript'],
        featured_image: '../assets/05-nrwl-nx-workshop.png',
        project_link: 'https://github.com/PiotrKieltyka/angular-workshop',
        button_icon: 'fab fa-angular fa-lg',
        button_text: 'Visit project',
        categories: 'development',
    },
    {
        position: 'left',
        title: 'userApp',
        lead_text: 'Project created to develop my programming skills',
        date: '2018-11-28',
        tags: ['Angular', 'Material', 'TypeScript', 'SASS'],
        featured_image: '../assets/02-userApp-frontend.png',
        project_link: 'https://github.com/PiotrKieltyka/userApp-nodeServer',
        button_icon: 'fab fa-angular fa-lg',
        button_text: 'Visit project',
        categories: 'development',
    },
    {
        position: 'right',
        title: 'userApp NodeJS server',
        lead_text: 'API written in TypeScript using Node, Express and connected to MongoDB via Mongoose',
        date: '2018-11-29',
        tags: ['TypeScript', 'Express', 'NodeJS', 'MongoDB', 'API'],
        featured_image: '../assets/01_userApp-nodeServer.png',
        project_link: 'https://github.com/PiotrKieltyka/userApp',
        button_icon: 'fab fa-node-js fa-lg',
        button_text: 'Visit project',
        categories: 'development',
    },
    {
        position: 'left',
        title: 'Monitoring App',
        lead_text: 'Project created for an android phones and tablets to monitoring production & packaging products',
        date: '2019-01-29',
        tags: ['Angular', 'Material', 'TypeScript', 'Android', 'RWD', 'JSON'],
        featured_image: '../assets/04-rwd-production-monitor.png',
        project_link: '',
        button_icon: '',
        button_text: '',
        categories: 'development',
    },
    {
        position: 'right',
        title: 'Apartamenty na Polanie',
        lead_text: 'Project created for my residents\' association',
        date: '2015-05-08',
        tags: ['HTML', 'SASS', 'JavaScript'],
        featured_image: '../assets/03-anp1-website.png',
        project_link: 'https://anp1.pl',
        button_icon: 'fas fa-users fa-lg',
        button_text: 'Visit project',
        categories: '',
    },

];

// {
//     position: '',
//     title: '',
//     lead_text: '',
//     date: '',
//     tags: [],
//     featured_image: '',
//     button_icon: '',
//     button_text: '',
//     categories: '',
//     project_link: ''
// },
